// This code allows the Menu links to open and close

$(document).ready(function(){
// A-G
  $(".A-G").click(function(){
      $(".A-G-toggle").toggle();
      $("a.A-G").toggleClass("letters-selected");
  });
  // ANIMATIONS
  $(".animations").click(function(){
      $(".animations-toggle").toggle();
      $(".animations").toggleClass("main-topic-selected");
  });
  $(".animations-css3").click(function(){
      $(".animations-css3-toggle").toggle();
  });
  $(".two-d-transforms-css3").click(function(){
      $(".two-d-transforms-css3-toggle").toggle();
  });
  $(".three-d-transforms-css3").click(function(){
      $(".three-d-transforms-css3-toggle").toggle();
  });
  $(".transitions-css3").click(function(){
      $(".transitions-css3-toggle").toggle();
  });
  // BORDERS & OUTLINES
  $(".borders-outlines").click(function(){
      $(".borders-outlines-toggle").toggle();
      $(".borders-outlines").toggleClass("main-topic-selected");
  });
  $(".border-images-css3").click(function(){
      $(".border-images-css3-toggle").toggle();
  });
  $(".borders-css").click(function(){
      $(".borders-css-toggle").toggle();
  });
  $(".outlines-css").click(function(){
      $(".outlines-css-toggle").toggle();
  });
  $(".rounded-corners-css3").click(function(){
      $(".rounded-corners-css3-toggle").toggle();
  });
  // BOXES
  $(".boxes").click(function(){
      $(".boxes-toggle").toggle();
      $(".boxes").toggleClass("main-topic-selected");
  });
  $(".box-model-css").click(function(){
      $(".box-model-css-toggle").toggle();
  });
  $(".box-sizing-css3").click(function(){
      $(".box-sizing-css3-toggle").toggle();
  });
  $(".flexbox-css3").click(function(){
      $(".flexbox-css3-toggle").toggle();
  });
  $(".user-interface-css3").click(function(){
      $(".user-interface-css3-toggle").toggle();
  });
  // BUTTONS & ICONS
  $(".buttons-icons").click(function(){
      $(".buttons-icons-toggle").toggle();
      $(".buttons-icons").toggleClass("main-topic-selected");
  });
  $(".buttons-css3").click(function(){
      $(".buttons-css3-toggle").toggle();
  });
  $(".icons-css").click(function(){
      $(".icons-css-toggle").toggle();
  });
  // COLOR
  $(".color").click(function(){
      $(".color-toggle").toggle();
      $(".color").toggleClass("main-topic-selected");
  });
  $(".color-css").click(function(){
      $(".color-css-toggle").toggle();
  });
  $(".colors-css3").click(function(){
      $(".colors-css3-toggle").toggle();
  });
  $(".gradients-css3").click(function(){
      $(".gradients-css3-toggle").toggle();
  });
  // COMBINATORS
  $(".combinators").click(function(){
      $(".combinators-toggle").toggle();
      $(".combinators").toggleClass("main-topic-selected");
  });
  $(".combinators-css").click(function(){
      $(".combinators-css-toggle").toggle();
  });
  // COUNTERS & PAGINATION
  $(".counters-pagination").click(function(){
      $(".counters-pagination-toggle").toggle();
      $(".counters-pagination").toggleClass("main-topic-selected");
  });
  $(".counters-css").click(function(){
      $(".counters-css-toggle").toggle();
  });
  $(".pagination-css3").click(function(){
      $(".pagination-css3-toggle").toggle();
  });
  // DISPLAY
  $(".display").click(function(){
      $(".display-toggle").toggle();
      $(".display").toggleClass("main-topic-selected");
  });
  $(".display-css").click(function(){
      $(".display-css-toggle").toggle();
  });
  // FLOAT
  $(".float").click(function(){
      $(".float-toggle").toggle();
      $(".float").toggleClass("main-topic-selected");
  });
  $(".float-css").click(function(){
      $(".float-css-toggle").toggle();
  });
  // FORMS
  $(".forms").click(function(){
      $(".forms-toggle").toggle();
      $(".forms").toggleClass("main-topic-selected");
  });
  $(".forms-css").click(function(){
      $(".forms-css-toggle").toggle();
  });
  // FRAMEWORKS & TEMPLATES
  $(".frameworks-templates").click(function(){
      $(".frameworks-templates-toggle").toggle();
      $(".frameworks-templates").toggleClass("main-topic-selected");
  });
  $(".frameworks-rwd").click(function(){
      $(".frameworks-rwd-toggle").toggle();
  });
  $(".templates-rwd").click(function(){
      $(".templates-rwd-toggle").toggle();
  });
// H-N
  $(".H-N").click(function(){
      $(".H-N-toggle").toggle();
      $("a.H-N").toggleClass("letters-selected");
  });
  // HEIGHT & WIDTH
  $(".height-width").click(function(){
      $(".height-width-toggle").toggle();
      $(".height-width").toggleClass("main-topic-selected");
  });
  $(".height-width-css").click(function(){
      $(".height-width-css-toggle").toggle();
  });
  $(".max-width-css").click(function(){
      $(".max-width-css-toggle").toggle();
  });
  // IMAGES
  $(".images").click(function(){
      $(".images-toggle").toggle();
      $(".images").toggleClass("main-topic-selected");
  });
  $(".backgrounds-css3").click(function(){
      $(".backgrounds-css3-toggle").toggle();
  });
  $(".images-css").click(function(){
      $(".images-css-toggle").toggle();
  });
  $(".images-css3").click(function(){
      $(".images-css3-toggle").toggle();
  });
  $(".images-rwd").click(function(){
      $(".images-rwd-toggle").toggle();
  });
  $(".image-gallery-css").click(function(){
      $(".image-gallery-css-toggle").toggle();
  });
  $(".image-sprites-css").click(function(){
      $(".image-sprites-css-toggle").toggle();
  });
  // INLINE-BLOCK
  $(".inline-block").click(function(){
      $(".inline-block-toggle").toggle();
      $(".inline-block").toggleClass("main-topic-selected");
  });
  $(".inline-block-css").click(function(){
      $(".inline-block-css-toggle").toggle();
  });
  // INTRODUCTIONS
  $(".introductions").click(function(){
      $(".introductions-toggle").toggle();
      $(".introductions").toggleClass("main-topic-selected");
  });
  $(".introduction-css3").click(function(){
      $(".introduction-css3-toggle").toggle();
  });
  $(".introduction-rwd").click(function(){
      $(".introduction-rwd-toggle").toggle();
  });
  // LINKS
  $(".links").click(function(){
      $(".links-toggle").toggle();
      $(".links").toggleClass("main-topic-selected");
  });
  $(".links-css").click(function(){
      $(".links-css-toggle").toggle();
  });
  // LISTS
  $(".lists").click(function(){
      $(".lists-toggle").toggle();
      $(".lists").toggleClass("main-topic-selected");
  });
  $(".lists-css").click(function(){
      $(".lists-css-toggle").toggle();
  });
  // MARGINS & PADDING
  $(".margins-padding").click(function(){
      $(".margins-padding-toggle").toggle();
      $(".margins-padding").toggleClass("main-topic-selected");
  });
  $(".margins-css").click(function(){
      $(".margins-css-toggle").toggle();
  });
  $(".padding-css").click(function(){
      $(".padding-css-toggle").toggle();
  });
  // MEDIA QUERIES
  $(".media-queries").click(function(){
      $(".media-queries-toggle").toggle();
      $(".media-queries").toggleClass("main-topic-selected");
  });
  $(".media-queries-css3").click(function(){
      $(".media-queries-css3-toggle").toggle();
  });
  $(".media-queries-rwd").click(function(){
      $(".media-queries-rwd-toggle").toggle();
  });
  $(".mq-examples-css3").click(function(){
      $(".mq-examples-css3-toggle").toggle();
  });
  $(".viewport-rwd").click(function(){
      $(".viewport-rwd-toggle").toggle();
  });
// O-T
  $(".O-T").click(function(){
      $(".O-T-toggle").toggle();
      $("a.O-T").toggleClass("letters-selected");
  });
  // OPACITY
  $(".opacity").click(function(){
      $(".opacity-toggle").toggle();
      $(".opacity").toggleClass("main-topic-selected");
  });
  $(".opacity-css").click(function(){
      $(".opacity-css-toggle").toggle();
  });
  // OVERFLOW
  $(".overflow").click(function(){
      $(".overflow-toggle").toggle();
      $(".overflow").toggleClass("main-topic-selected");
  });
  $(".overflow-css").click(function(){
      $(".overflow-css-toggle").toggle();
  });
  // POSITION
  $(".position").click(function(){
      $(".position-toggle").toggle();
      $(".position").toggleClass("main-topic-selected");
  });
  $(".align-css").click(function(){
      $(".align-css-toggle").toggle();
  });
  $(".position-css").click(function(){
      $(".position-css-toggle").toggle();
  });
  // PSEUDO
  $(".pseudo").click(function(){
      $(".pseudo-toggle").toggle();
      $(".pseudo").toggleClass("main-topic-selected");
  });
  $(".pseudo-class-css").click(function(){
      $(".pseudo-class-css-toggle").toggle();
  });
  $(".pseudo-element-css").click(function(){
      $(".pseudo-element-css-toggle").toggle();
  });
  // SHADOWS
  $(".shadows").click(function(){
      $(".shadows-toggle").toggle();
      $(".shadows").toggleClass("main-topic-selected");
  });
  $(".shadow-effects-css3").click(function(){
      $(".shadow-effects-css3-toggle").toggle();
  });
  // SYTAX & SELECTORS
  $(".syntax-selectors").click(function(){
      $(".syntax-selectors-toggle").toggle();
      $(".syntax-selectors").toggleClass("main-topic-selected");
  });
  $(".attribute-selectors-css").click(function(){
      $(".attribute-selectors-css-toggle").toggle();
  });
  $(".syntax-selectors-css").click(function(){
      $(".syntax-selectors-css-toggle").toggle();
  });
  // TABLE OF CONTENTS
  $(".table-of-contents").click(function(){
      $(".table-of-contents-toggle").toggle();
      $(".table-of-contents").toggleClass("main-topic-selected");
  });
  $(".table-of-contents-css").click(function(){
      $(".table-of-contents-css-toggle").toggle();
  });
  $(".table-of-contents-css3").click(function(){
      $(".table-of-contents-css3-toggle").toggle();
  });
  // TABLES & COLUMNS
  $(".tables-columns").click(function(){
      $(".tables-columns-toggle").toggle();
      $(".tables-columns").toggleClass("main-topic-selected");
  });
  $(".grid-view-rwd").click(function(){
      $(".grid-view-rwd-toggle").toggle();
  });
  $(".columns-css3").click(function(){
      $(".columns-css3-toggle").toggle();
  });
  $(".tables-css").click(function(){
      $(".tables-css-toggle").toggle();
  });
  // TEXT
  $(".text").click(function(){
      $(".text-toggle").toggle();
      $(".text").toggleClass("main-topic-selected");
  });
  $(".fonts-css").click(function(){
      $(".fonts-css-toggle").toggle();
  });
  $(".fonts-css3").click(function(){
      $(".fonts-css3-toggle").toggle();
  });
  $(".text-css").click(function(){
      $(".text-css-toggle").toggle();
  });
  $(".text-css3").click(function(){
      $(".text-css3-toggle").toggle();
  });
  // TOOLBARS
  $(".toolbars").click(function(){
      $(".toolbars-toggle").toggle();
      $(".toolbars").toggleClass("main-topic-selected");
  });
  $(".dropdowns-css").click(function(){
      $(".dropdowns-css-toggle").toggle();
  });
  $(".navigation-bar-css").click(function(){
      $(".navigation-bar-css-toggle").toggle();
  });
  $(".tooltips-css").click(function(){
      $(".tooltips-css-toggle").toggle();
  });
// U-Z
  $(".U-Z").click(function(){
      $(".U-Z-toggle").toggle();
      $("a.U-Z").toggleClass("letters-selected");
  });
  // VIDEOS
  $(".videos").click(function(){
      $(".videos-toggle").toggle();
      $(".videos").toggleClass("main-topic-selected");
  });
  $(".videos-rwd").click(function(){
      $(".videos-rwd-toggle").toggle();
  });
  // WAYS TO INSERT
  $(".ways-to-insert").click(function(){
      $(".ways-to-insert-toggle").toggle();
      $(".ways-to-insert").toggleClass("main-topic-selected");
  });
  $(".ways-to-insert-css").click(function(){
      $(".ways-to-insert-css-toggle").toggle();
  });
});
